Repository coala/documentation, pull requests merged in 2018-04, with the labels that each got.

#546 README.rst: Update build instructions
  README.rst
Labels: area/usability, difficulty/low, importance/low, process/approved, size/XS

#549 Add coala_quickstart.rst
  Users/coala_quickstart.rst
  index.rst
Labels: area/documentation, process/pending review, size/XS

#537 Tutorial.rst: Rewrite all mentions of Default
  Users/Tutorial.rst
Labels: area/documentation, difficulty/low, importance/high, process/approved, size/XS

#551 .travis.yml: Enable travis-buddy
  .travis.yml
Labels: process/pending review, size/XS
