Repository coala/documentation, pull requests merged in 2018-03, with the labels that each got.

#533 PULL_REQUEST_TEMPLATE.md: cobot --> corobo
  PULL_REQUEST_TEMPLATE.md
Labels: difficulty/newcomer, process/approved, size/XS

#517 Correct grammatical error: an user --> a user
  index.rst
Labels: area/documentation, difficulty/newcomer, process/approved, size/XS

#510 Tutorial.rst: Change documentation about .coafile
  Users/Tutorial.rst
Labels: area/documentation, difficulty/newcomer, importance/high, process/approved, size/XS

#504 Install.rst: Adding pipenv support
  .gitignore
  Users/Install.rst
Labels: area/documentation, difficulty/newcomer, process/approved, size/XS, status/stale

#500 Tutorial.rst: Documentation of `--apply-patches`
  Users/Tutorial.rst
Labels: process/approved, size/XS, status/stale

#536 FAQ.rst: Fix "ask us!" link
  Help/FAQ.rst
Labels: bug, difficulty/newcomer, importance/high, process/approved, size/XS

#542 Install.rst: Fix docs failing build
  Users/Install.rst
Labels: area/documentation, difficulty/low, difficulty/newcomer, importance/medium, process/approved, size/XS

#532 coafile.rst: Fix bad code markup
  Users/coafile.rst
Labels: area/documentation, difficulty/newcomer, process/approved, size/XS

#494 Users/Docker_Image.rst: Fix copyright violation
  Users/Docker_Image.rst
Labels: importance/critical, process/approved, size/XS, status/stale
